site_name: Premo Robotics Motor Motion Control Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - content.code.copy
    - content.tooltips

plugins:
  - offline
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
