// Code generated by protoc-gen-zig
///! package mmc
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;
/// import package mmc.core
const mmc_core = @import("mmc/core.pb.zig");
/// import package mmc.command
const mmc_command = @import("mmc/command.pb.zig");
/// import package mmc.info
const mmc_info = @import("mmc/info.pb.zig");

/// Carrier motor control kind.
pub const Control = enum(i32) {
    CONTROL_UNSPECIFIED = 0,
    CONTROL_POSITION = 1,
    CONTROL_VELOCITY = 2,
    _,
};

/// Request message. All client-to-server messages should be of this message
/// type.
pub const Request = struct {
    body: ?body_union = null,

    pub const _body_case = enum {
        core,
        command,
        info,
    };
    pub const body_union = union(_body_case) {
        core: mmc_core.Request,
        command: mmc_command.Request,
        info: mmc_info.Request,
        pub const _desc_table = .{
            .core = fd(1, .submessage),
            .command = fd(2, .submessage),
            .info = fd(3, .submessage),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .oneof = body_union }),
    };

    pub const Error = enum(i32) {
        MMC_REQUEST_ERROR_UNSPECIFIED = 0,
        MMC_REQUEST_ERROR_INVALID_MESSAGE = 1,
        _,
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Response message. All server-to-client messages will be of this message
/// type.
pub const Response = struct {
    body: ?body_union = null,

    pub const _body_case = enum {
        core,
        command,
        info,
        request_error,
    };
    pub const body_union = union(_body_case) {
        core: mmc_core.Response,
        command: mmc_command.Response,
        info: mmc_info.Response,
        request_error: Request.Error,
        pub const _desc_table = .{
            .core = fd(1, .submessage),
            .command = fd(2, .submessage),
            .info = fd(3, .submessage),
            .request_error = fd(4, .@"enum"),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .oneof = body_union }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};
