// Code generated by protoc-gen-zig
///! package mmc.info
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;
/// import package root
const root = @import("../root.pb.zig");

pub const Request = struct {
    body: ?body_union = null,

    pub const _body_case = enum {
        command,
        track,
    };
    pub const body_union = union(_body_case) {
        command: Request.Command,
        track: Request.Track,
        pub const _desc_table = .{
            .command = fd(1, .submessage),
            .track = fd(2, .submessage),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .oneof = body_union }),
    };

    pub const Error = enum(i32) {
        INFO_REQUEST_ERROR_UNSPECIFIED = 0,
        INFO_REQUEST_ERROR_INVALID_LINE = 1,
        INFO_REQUEST_ERROR_INVALID_AXIS = 2,
        INFO_REQUEST_ERROR_INVALID_DRIVER = 3,
        INFO_REQUEST_ERROR_MISSING_PARAMETER = 4,
        INFO_REQUEST_ERROR_COMMAND_NOT_FOUND = 5,
        INFO_REQUEST_ERROR_INVALID_COMMAND = 6,
        INFO_REQUEST_ERROR_INVALID_CARRIER = 7,
        _,
    };

    /// Request for status of specified command ID from the server. If no command
    /// ID is provided, then request for status of all commands from the server.
    ///
    /// Expected response: `mmc.Response.body.info.body.commands`
    pub const Command = struct {
        id: ?u32 = null,

        pub const _desc_table = .{
            .id = fd(1, .{ .scalar = .uint32 }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Request track state information from server. One or more of the `info_`
    /// flags must be enabled to select the kind of track information desired.
    /// A filter may be optionally provided to limit the source of information
    /// from the track.
    ///
    /// Expected response: `mmc.Response.body.info.body.track`
    pub const Track = struct {
        lines: std.ArrayList(u32) = .empty,
        info_driver_state: bool = false,
        info_driver_errors: bool = false,
        info_axis_state: bool = false,
        info_axis_errors: bool = false,
        info_carrier_state: bool = false,
        register_x: bool = false,
        register_y: bool = false,
        register_ww: bool = false,
        register_wr: bool = false,
        filter: ?filter_union = null,

        pub const _filter_case = enum {
            drivers,
            axes,
            carriers,
        };
        pub const filter_union = union(_filter_case) {
            drivers: root.Range,
            axes: root.Range,
            carriers: Request.Track.Ids,
            pub const _desc_table = .{
                .drivers = fd(8, .submessage),
                .axes = fd(9, .submessage),
                .carriers = fd(10, .submessage),
            };
        };

        pub const _desc_table = .{
            .lines = fd(7, .{ .packed_repeated = .{ .scalar = .uint32 } }),
            .info_driver_state = fd(2, .{ .scalar = .bool }),
            .info_driver_errors = fd(3, .{ .scalar = .bool }),
            .info_axis_state = fd(4, .{ .scalar = .bool }),
            .info_axis_errors = fd(5, .{ .scalar = .bool }),
            .info_carrier_state = fd(6, .{ .scalar = .bool }),
            .register_x = fd(11, .{ .scalar = .bool }),
            .register_y = fd(12, .{ .scalar = .bool }),
            .register_ww = fd(13, .{ .scalar = .bool }),
            .register_wr = fd(14, .{ .scalar = .bool }),
            .filter = fd(null, .{ .oneof = filter_union }),
        };

        /// List of IDs. At least one ID must be provided.
        pub const Ids = struct {
            ids: std.ArrayList(u32) = .empty,

            pub const _desc_table = .{
                .ids = fd(1, .{ .packed_repeated = .{ .scalar = .uint32 } }),
            };

            /// Encodes the message to the writer
            /// The allocator is used to generate submessages internally.
            /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return protobuf.encode(writer, allocator, self);
            }

            /// Decodes the message from the bytes read from the reader.
            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return protobuf.decode(@This(), reader, allocator);
            }

            /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
            /// field at a time without allocating. See `src/stream.zig`.
            pub const StreamDecoder = protobuf.StreamDecoder(@This());

            /// Deinitializes and frees the memory associated with the message.
            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return protobuf.deinit(allocator, self);
            }

            /// Duplicates the message.
            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return protobuf.dupe(@This(), self, allocator);
            }

            /// Decodes the message from the JSON string.
            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return protobuf.json.decode(@This(), input, options, allocator);
            }

            /// Encodes the message to a JSON string.
            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                pb_options: protobuf.json.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return protobuf.json.encode(self, options, pb_options, allocator);
            }

            /// This method is used by std.json
            /// internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return protobuf.json.parse(@This(), allocator, source, options);
            }
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

pub const Response = struct {
    body: ?body_union = null,

    pub const _body_case = enum {
        command,
        track,
        request_error,
    };
    pub const body_union = union(_body_case) {
        command: Response.Commands,
        track: Response.Track,
        request_error: Request.Error,
        pub const _desc_table = .{
            .command = fd(1, .submessage),
            .track = fd(2, .submessage),
            .request_error = fd(3, .@"enum"),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .oneof = body_union }),
    };

    pub const Track = struct {
        lines: std.ArrayList(Response.Line) = .empty,

        pub const _desc_table = .{
            .lines = fd(1, .{ .repeated = .submessage }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    pub const Commands = struct {
        items: std.ArrayList(Response.Command) = .empty,

        pub const _desc_table = .{
            .items = fd(1, .{ .repeated = .submessage }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    pub const Command = struct {
        id: u32 = 0,
        status: Response.Command.Status = @enumFromInt(0),
        @"error": ?Response.Command.Error = null,

        pub const _desc_table = .{
            .id = fd(1, .{ .scalar = .uint32 }),
            .status = fd(2, .@"enum"),
            .@"error" = fd(3, .@"enum"),
        };

        pub const Status = enum(i32) {
            COMMAND_STATUS_UNSPECIFIED = 0,
            COMMAND_STATUS_PROGRESSING = 1,
            COMMAND_STATUS_COMPLETED = 2,
            COMMAND_STATUS_FAILED = 3,
            _,
        };

        pub const Error = enum(i32) {
            COMMAND_ERROR_UNSPECIFIED = 0,
            COMMAND_ERROR_INVALID_SYSTEM_STATE = 1,
            COMMAND_ERROR_INVALID_CARRIER_ID = 2,
            COMMAND_ERROR_DRIVER_DISCONNECTED = 3,
            COMMAND_ERROR_UNEXPECTED = 4,
            COMMAND_ERROR_CARRIER_NOT_FOUND = 5,
            COMMAND_ERROR_CARRIER_ALREADY_INITIALIZED = 6,
            COMMAND_ERROR_DRIVER_STOPPED = 7,
            COMMAND_ERROR_INVALID_CARRIER_TARGET = 8,
            COMMAND_ERROR_CONFLICTING_CARRIER_ID = 9,
            _,
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    pub const Line = struct {
        id: u32 = 0,
        driver_state: std.ArrayList(Response.Line.Driver.State) = .empty,
        driver_errors: std.ArrayList(Response.Line.Driver.Error) = .empty,
        axis_state: std.ArrayList(Response.Line.Axis.State) = .empty,
        axis_errors: std.ArrayList(Response.Line.Axis.Error) = .empty,
        carrier_state: std.ArrayList(Response.Line.Carrier.State) = .empty,
        register_x: std.ArrayList(Response.Line.Register) = .empty,
        register_y: std.ArrayList(Response.Line.Register) = .empty,
        register_ww: std.ArrayList(Response.Line.Register) = .empty,
        register_wr: std.ArrayList(Response.Line.Register) = .empty,

        pub const _desc_table = .{
            .id = fd(1, .{ .scalar = .uint32 }),
            .driver_state = fd(2, .{ .repeated = .submessage }),
            .driver_errors = fd(3, .{ .repeated = .submessage }),
            .axis_state = fd(4, .{ .repeated = .submessage }),
            .axis_errors = fd(5, .{ .repeated = .submessage }),
            .carrier_state = fd(6, .{ .repeated = .submessage }),
            .register_x = fd(7, .{ .repeated = .submessage }),
            .register_y = fd(8, .{ .repeated = .submessage }),
            .register_ww = fd(9, .{ .repeated = .submessage }),
            .register_wr = fd(10, .{ .repeated = .submessage }),
        };

        pub const Register = struct {
            driver: u32 = 0,
            value: std.ArrayList(u64) = .empty,

            pub const _desc_table = .{
                .driver = fd(1, .{ .scalar = .uint32 }),
                .value = fd(2, .{ .packed_repeated = .{ .scalar = .uint64 } }),
            };

            /// Encodes the message to the writer
            /// The allocator is used to generate submessages internally.
            /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return protobuf.encode(writer, allocator, self);
            }

            /// Decodes the message from the bytes read from the reader.
            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return protobuf.decode(@This(), reader, allocator);
            }

            /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
            /// field at a time without allocating. See `src/stream.zig`.
            pub const StreamDecoder = protobuf.StreamDecoder(@This());

            /// Deinitializes and frees the memory associated with the message.
            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return protobuf.deinit(allocator, self);
            }

            /// Duplicates the message.
            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return protobuf.dupe(@This(), self, allocator);
            }

            /// Decodes the message from the JSON string.
            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return protobuf.json.decode(@This(), input, options, allocator);
            }

            /// Encodes the message to a JSON string.
            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                pb_options: protobuf.json.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return protobuf.json.encode(self, options, pb_options, allocator);
            }

            /// This method is used by std.json
            /// internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return protobuf.json.parse(@This(), allocator, source, options);
            }
        };

        pub const Axis = struct {
            pub const _desc_table = .{};

            pub const State = struct {
                id: u32 = 0,
                motor_active: bool = false,
                waiting_pull: bool = false,
                waiting_push: bool = false,
                carrier: u32 = 0,
                hall_alarm_back: bool = false,
                hall_alarm_front: bool = false,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .motor_active = fd(2, .{ .scalar = .bool }),
                    .waiting_pull = fd(3, .{ .scalar = .bool }),
                    .waiting_push = fd(4, .{ .scalar = .bool }),
                    .carrier = fd(5, .{ .scalar = .uint32 }),
                    .hall_alarm_back = fd(6, .{ .scalar = .bool }),
                    .hall_alarm_front = fd(7, .{ .scalar = .bool }),
                };

                /// Encodes the message to the writer
                /// The allocator is used to generate submessages internally.
                /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return protobuf.encode(writer, allocator, self);
                }

                /// Decodes the message from the bytes read from the reader.
                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return protobuf.decode(@This(), reader, allocator);
                }

                /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
                /// field at a time without allocating. See `src/stream.zig`.
                pub const StreamDecoder = protobuf.StreamDecoder(@This());

                /// Deinitializes and frees the memory associated with the message.
                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return protobuf.deinit(allocator, self);
                }

                /// Duplicates the message.
                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return protobuf.dupe(@This(), self, allocator);
                }

                /// Decodes the message from the JSON string.
                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return protobuf.json.decode(@This(), input, options, allocator);
                }

                /// Encodes the message to a JSON string.
                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    pb_options: protobuf.json.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return protobuf.json.encode(self, options, pb_options, allocator);
                }

                /// This method is used by std.json
                /// internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return protobuf.json.parse(@This(), allocator, source, options);
                }
            };

            pub const Error = struct {
                id: u32 = 0,
                overcurrent: bool = false,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .overcurrent = fd(2, .{ .scalar = .bool }),
                };

                /// Encodes the message to the writer
                /// The allocator is used to generate submessages internally.
                /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return protobuf.encode(writer, allocator, self);
                }

                /// Decodes the message from the bytes read from the reader.
                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return protobuf.decode(@This(), reader, allocator);
                }

                /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
                /// field at a time without allocating. See `src/stream.zig`.
                pub const StreamDecoder = protobuf.StreamDecoder(@This());

                /// Deinitializes and frees the memory associated with the message.
                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return protobuf.deinit(allocator, self);
                }

                /// Duplicates the message.
                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return protobuf.dupe(@This(), self, allocator);
                }

                /// Decodes the message from the JSON string.
                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return protobuf.json.decode(@This(), input, options, allocator);
                }

                /// Encodes the message to a JSON string.
                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    pb_options: protobuf.json.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return protobuf.json.encode(self, options, pb_options, allocator);
                }

                /// This method is used by std.json
                /// internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return protobuf.json.parse(@This(), allocator, source, options);
                }
            };

            /// Encodes the message to the writer
            /// The allocator is used to generate submessages internally.
            /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return protobuf.encode(writer, allocator, self);
            }

            /// Decodes the message from the bytes read from the reader.
            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return protobuf.decode(@This(), reader, allocator);
            }

            /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
            /// field at a time without allocating. See `src/stream.zig`.
            pub const StreamDecoder = protobuf.StreamDecoder(@This());

            /// Deinitializes and frees the memory associated with the message.
            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return protobuf.deinit(allocator, self);
            }

            /// Duplicates the message.
            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return protobuf.dupe(@This(), self, allocator);
            }

            /// Decodes the message from the JSON string.
            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return protobuf.json.decode(@This(), input, options, allocator);
            }

            /// Encodes the message to a JSON string.
            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                pb_options: protobuf.json.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return protobuf.json.encode(self, options, pb_options, allocator);
            }

            /// This method is used by std.json
            /// internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return protobuf.json.parse(@This(), allocator, source, options);
            }
        };

        pub const Driver = struct {
            pub const _desc_table = .{};

            pub const State = struct {
                id: u32 = 0,
                connected: bool = false,
                busy: bool = false,
                motor_disabled: bool = false,
                stopped: bool = false,
                paused: bool = false,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .connected = fd(2, .{ .scalar = .bool }),
                    .busy = fd(3, .{ .scalar = .bool }),
                    .motor_disabled = fd(4, .{ .scalar = .bool }),
                    .stopped = fd(5, .{ .scalar = .bool }),
                    .paused = fd(6, .{ .scalar = .bool }),
                };

                /// Encodes the message to the writer
                /// The allocator is used to generate submessages internally.
                /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return protobuf.encode(writer, allocator, self);
                }

                /// Decodes the message from the bytes read from the reader.
                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return protobuf.decode(@This(), reader, allocator);
                }

                /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
                /// field at a time without allocating. See `src/stream.zig`.
                pub const StreamDecoder = protobuf.StreamDecoder(@This());

                /// Deinitializes and frees the memory associated with the message.
                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return protobuf.deinit(allocator, self);
                }

                /// Duplicates the message.
                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return protobuf.dupe(@This(), self, allocator);
                }

                /// Decodes the message from the JSON string.
                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return protobuf.json.decode(@This(), input, options, allocator);
                }

                /// Encodes the message to a JSON string.
                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    pb_options: protobuf.json.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return protobuf.json.encode(self, options, pb_options, allocator);
                }

                /// This method is used by std.json
                /// internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return protobuf.json.parse(@This(), allocator, source, options);
                }
            };

            pub const Error = struct {
                id: u32 = 0,
                control_loop_time_exceeded: bool = false,
                inverter_overheat: bool = false,
                undervoltage: bool = false,
                overvoltage: bool = false,
                comm_error_prev: bool = false,
                comm_error_next: bool = false,

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .control_loop_time_exceeded = fd(2, .{ .scalar = .bool }),
                    .inverter_overheat = fd(3, .{ .scalar = .bool }),
                    .undervoltage = fd(4, .{ .scalar = .bool }),
                    .overvoltage = fd(5, .{ .scalar = .bool }),
                    .comm_error_prev = fd(6, .{ .scalar = .bool }),
                    .comm_error_next = fd(7, .{ .scalar = .bool }),
                };

                /// Encodes the message to the writer
                /// The allocator is used to generate submessages internally.
                /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return protobuf.encode(writer, allocator, self);
                }

                /// Decodes the message from the bytes read from the reader.
                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return protobuf.decode(@This(), reader, allocator);
                }

                /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
                /// field at a time without allocating. See `src/stream.zig`.
                pub const StreamDecoder = protobuf.StreamDecoder(@This());

                /// Deinitializes and frees the memory associated with the message.
                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return protobuf.deinit(allocator, self);
                }

                /// Duplicates the message.
                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return protobuf.dupe(@This(), self, allocator);
                }

                /// Decodes the message from the JSON string.
                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return protobuf.json.decode(@This(), input, options, allocator);
                }

                /// Encodes the message to a JSON string.
                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    pb_options: protobuf.json.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return protobuf.json.encode(self, options, pb_options, allocator);
                }

                /// This method is used by std.json
                /// internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return protobuf.json.parse(@This(), allocator, source, options);
                }
            };

            /// Encodes the message to the writer
            /// The allocator is used to generate submessages internally.
            /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return protobuf.encode(writer, allocator, self);
            }

            /// Decodes the message from the bytes read from the reader.
            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return protobuf.decode(@This(), reader, allocator);
            }

            /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
            /// field at a time without allocating. See `src/stream.zig`.
            pub const StreamDecoder = protobuf.StreamDecoder(@This());

            /// Deinitializes and frees the memory associated with the message.
            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return protobuf.deinit(allocator, self);
            }

            /// Duplicates the message.
            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return protobuf.dupe(@This(), self, allocator);
            }

            /// Decodes the message from the JSON string.
            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return protobuf.json.decode(@This(), input, options, allocator);
            }

            /// Encodes the message to a JSON string.
            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                pb_options: protobuf.json.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return protobuf.json.encode(self, options, pb_options, allocator);
            }

            /// This method is used by std.json
            /// internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return protobuf.json.parse(@This(), allocator, source, options);
            }
        };

        pub const Carrier = struct {
            pub const _desc_table = .{};

            pub const State = struct {
                id: u32 = 0,
                position: f32 = 0,
                axis_main: u32 = 0,
                axis_auxiliary: ?u32 = null,
                cas_disabled: bool = false,
                cas_triggered: bool = false,
                state: Response.Line.Carrier.State.State = @enumFromInt(0),

                pub const _desc_table = .{
                    .id = fd(1, .{ .scalar = .uint32 }),
                    .position = fd(2, .{ .scalar = .float }),
                    .axis_main = fd(3, .{ .scalar = .uint32 }),
                    .axis_auxiliary = fd(4, .{ .scalar = .uint32 }),
                    .cas_disabled = fd(5, .{ .scalar = .bool }),
                    .cas_triggered = fd(6, .{ .scalar = .bool }),
                    .state = fd(7, .@"enum"),
                };

                pub const State = enum(i32) {
                    CARRIER_STATE_NONE = 0,
                    CARRIER_STATE_CALIBRATING = 1,
                    CARRIER_STATE_CALIBRATE_COMPLETED = 2,
                    CARRIER_STATE_MOVING = 3,
                    CARRIER_STATE_MOVE_COMPLETED = 4,
                    CARRIER_STATE_INITIALIZING = 5,
                    CARRIER_STATE_INITIALIZE_COMPLETED = 6,
                    CARRIER_STATE_PUSHING = 7,
                    CARRIER_STATE_PULLING = 9,
                    CARRIER_STATE_OVERCURRENT = 11,
                    _,
                };

                /// Encodes the message to the writer
                /// The allocator is used to generate submessages internally.
                /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
                pub fn encode(
                    self: @This(),
                    writer: *std.Io.Writer,
                    allocator: std.mem.Allocator,
                ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                    return protobuf.encode(writer, allocator, self);
                }

                /// Decodes the message from the bytes read from the reader.
                pub fn decode(
                    reader: *std.Io.Reader,
                    allocator: std.mem.Allocator,
                ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                    return protobuf.decode(@This(), reader, allocator);
                }

                /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
                /// field at a time without allocating. See `src/stream.zig`.
                pub const StreamDecoder = protobuf.StreamDecoder(@This());

                /// Deinitializes and frees the memory associated with the message.
                pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                    return protobuf.deinit(allocator, self);
                }

                /// Duplicates the message.
                pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                    return protobuf.dupe(@This(), self, allocator);
                }

                /// Decodes the message from the JSON string.
                pub fn jsonDecode(
                    input: []const u8,
                    options: std.json.ParseOptions,
                    allocator: std.mem.Allocator,
                ) !std.json.Parsed(@This()) {
                    return protobuf.json.decode(@This(), input, options, allocator);
                }

                /// Encodes the message to a JSON string.
                pub fn jsonEncode(
                    self: @This(),
                    options: std.json.Stringify.Options,
                    pb_options: protobuf.json.Options,
                    allocator: std.mem.Allocator,
                ) ![]const u8 {
                    return protobuf.json.encode(self, options, pb_options, allocator);
                }

                /// This method is used by std.json
                /// internally for deserialization. DO NOT RENAME!
                pub fn jsonParse(
                    allocator: std.mem.Allocator,
                    source: anytype,
                    options: std.json.ParseOptions,
                ) !@This() {
                    return protobuf.json.parse(@This(), allocator, source, options);
                }
            };

            /// Encodes the message to the writer
            /// The allocator is used to generate submessages internally.
            /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return protobuf.encode(writer, allocator, self);
            }

            /// Decodes the message from the bytes read from the reader.
            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return protobuf.decode(@This(), reader, allocator);
            }

            /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
            /// field at a time without allocating. See `src/stream.zig`.
            pub const StreamDecoder = protobuf.StreamDecoder(@This());

            /// Deinitializes and frees the memory associated with the message.
            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return protobuf.deinit(allocator, self);
            }

            /// Duplicates the message.
            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return protobuf.dupe(@This(), self, allocator);
            }

            /// Decodes the message from the JSON string.
            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return protobuf.json.decode(@This(), input, options, allocator);
            }

            /// Encodes the message to a JSON string.
            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                pb_options: protobuf.json.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return protobuf.json.encode(self, options, pb_options, allocator);
            }

            /// This method is used by std.json
            /// internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return protobuf.json.parse(@This(), allocator, source, options);
            }
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};
