// Code generated by protoc-gen-zig
///! package mmc
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const RequestKind = enum(i32) {
    API_VERSION = 0,
    SERVER_VERSION = 1,
    LINE_CONFIG = 2,
    _,
};

pub const Request = struct {
    kind: RequestKind = @enumFromInt(0),

    pub const _desc_table = .{
        .kind = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Response = struct {
    body: ?body_union,

    pub const _body_case = enum {
        server_version,
        api_version,
        line_config,
    };
    pub const body_union = union(_body_case) {
        server_version: SemanticVersion,
        api_version: SemanticVersion,
        line_config: LineConfig,
        pub const _union_desc = .{
            .server_version = fd(1, .{ .SubMessage = {} }),
            .api_version = fd(2, .{ .SubMessage = {} }),
            .line_config = fd(3, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const LineConfig = struct {
        lines: ArrayList(Line),

        pub const _desc_table = .{
            .lines = fd(1, .{ .List = .{ .SubMessage = {} } }),
        };

        pub const Line = struct {
            axes: u32 = 0,
            name: ManagedString = .Empty,

            pub const _desc_table = .{
                .axes = fd(1, .{ .Varint = .Simple }),
                .name = fd(2, .String),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const SemanticVersion = struct {
        major: u32 = 0,
        minor: u32 = 0,
        patch: u32 = 0,

        pub const _desc_table = .{
            .major = fd(1, .{ .Varint = .Simple }),
            .minor = fd(2, .{ .Varint = .Simple }),
            .patch = fd(3, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Direction = enum(i32) {
    BACKWARD = 0,
    FORWARD = 1,
    _,
};

pub const CommandRequest = struct {
    body: ?body_union,

    pub const _body_case = enum {
        clear_errors,
        clear_carrier_info,
        reset_mcl,
        release_axis_servo,
        stop_pull_carrier,
        auto_initialize,
        stop_push_carrier,
        move_carrier,
        push_carrier,
        pull_carrier,
        isolate_carrier,
        calibrate,
        set_line_zero,
    };
    pub const body_union = union(_body_case) {
        clear_errors: ClearErrors,
        clear_carrier_info: ClearCarrierInfo,
        reset_mcl: NoParam,
        release_axis_servo: ReleaseAxisServo,
        stop_pull_carrier: StopPullCarrier,
        auto_initialize: AutoInitialize,
        stop_push_carrier: StopPushCarrier,
        move_carrier: MoveCarrier,
        push_carrier: PushCarrier,
        pull_carrier: PullCarrier,
        isolate_carrier: IsolateCarrier,
        calibrate: Calibrate,
        set_line_zero: SetLineZero,
        pub const _union_desc = .{
            .clear_errors = fd(1, .{ .SubMessage = {} }),
            .clear_carrier_info = fd(2, .{ .SubMessage = {} }),
            .reset_mcl = fd(3, .{ .SubMessage = {} }),
            .release_axis_servo = fd(4, .{ .SubMessage = {} }),
            .stop_pull_carrier = fd(5, .{ .SubMessage = {} }),
            .auto_initialize = fd(6, .{ .SubMessage = {} }),
            .stop_push_carrier = fd(7, .{ .SubMessage = {} }),
            .move_carrier = fd(8, .{ .SubMessage = {} }),
            .push_carrier = fd(9, .{ .SubMessage = {} }),
            .pull_carrier = fd(10, .{ .SubMessage = {} }),
            .isolate_carrier = fd(11, .{ .SubMessage = {} }),
            .calibrate = fd(12, .{ .SubMessage = {} }),
            .set_line_zero = fd(13, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const ReleaseAxisServo = struct {
        line_id: u32 = 0,
        axis_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const StopPullCarrier = struct {
        line_id: u32 = 0,
        axis_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const StopPushCarrier = struct {
        line_id: u32 = 0,
        axis_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const ClearErrors = struct {
        line_id: u32 = 0,
        axis_id: ?u32 = null,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const ClearCarrierInfo = struct {
        line_id: u32 = 0,
        axis_id: ?u32 = null,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const NoParam = struct {
        pub const _desc_table = .{};

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Calibrate = struct {
        line_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const SetLineZero = struct {
        line_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const AutoInitialize = struct {
        lines: ArrayList(Lines),

        pub const _desc_table = .{
            .lines = fd(1, .{ .List = .{ .SubMessage = {} } }),
        };

        pub const Lines = struct {
            line_id: u32 = 0,
            speed: u32 = 0,
            acceleration: u32 = 0,

            pub const _desc_table = .{
                .line_id = fd(1, .{ .Varint = .Simple }),
                .speed = fd(2, .{ .Varint = .Simple }),
                .acceleration = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const MoveCarrier = struct {
        line_id: u32 = 0,
        carrier_id: u32 = 0,
        speed: u32 = 0,
        acceleration: u32 = 0,
        control_kind: Control = @enumFromInt(0),
        target: ?target_union,

        pub const _target_case = enum {
            axis_id,
            location,
            distance,
        };
        pub const target_union = union(_target_case) {
            axis_id: u32,
            location: f32,
            distance: f32,
            pub const _union_desc = .{
                .axis_id = fd(5, .{ .Varint = .Simple }),
                .location = fd(6, .{ .FixedInt = .I32 }),
                .distance = fd(7, .{ .FixedInt = .I32 }),
            };
        };

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .carrier_id = fd(2, .{ .Varint = .Simple }),
            .speed = fd(3, .{ .Varint = .Simple }),
            .acceleration = fd(4, .{ .Varint = .Simple }),
            .control_kind = fd(8, .{ .Varint = .Simple }),
            .target = fd(null, .{ .OneOf = target_union }),
        };

        pub const Control = enum(i32) {
            POSITION = 0,
            SPEED = 1,
            _,
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const PushCarrier = struct {
        line_id: u32 = 0,
        carrier_id: u32 = 0,
        direction: Direction = @enumFromInt(0),
        speed: u32 = 0,
        acceleration: u32 = 0,
        axis_id: ?u32 = null,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .carrier_id = fd(2, .{ .Varint = .Simple }),
            .direction = fd(3, .{ .Varint = .Simple }),
            .speed = fd(4, .{ .Varint = .Simple }),
            .acceleration = fd(5, .{ .Varint = .Simple }),
            .axis_id = fd(6, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const PullCarrier = struct {
        line_id: u32 = 0,
        axis_id: u32 = 0,
        carrier_id: u32 = 0,
        direction: Direction = @enumFromInt(0),
        speed: u32 = 0,
        acceleration: u32 = 0,
        target: ?target_union,

        pub const _target_case = enum {
            axis,
            location,
        };
        pub const target_union = union(_target_case) {
            axis: u32,
            location: f32,
            pub const _union_desc = .{
                .axis = fd(7, .{ .Varint = .Simple }),
                .location = fd(8, .{ .FixedInt = .I32 }),
            };
        };

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
            .carrier_id = fd(3, .{ .Varint = .Simple }),
            .direction = fd(4, .{ .Varint = .Simple }),
            .speed = fd(5, .{ .Varint = .Simple }),
            .acceleration = fd(6, .{ .Varint = .Simple }),
            .target = fd(null, .{ .OneOf = target_union }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const IsolateCarrier = struct {
        line_id: u32 = 0,
        axis_id: u32 = 0,
        carrier_id: u32 = 0,
        direction: Direction = @enumFromInt(0),
        link_axis: ?Direction = null,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
            .carrier_id = fd(3, .{ .Varint = .Simple }),
            .direction = fd(4, .{ .Varint = .Simple }),
            .link_axis = fd(5, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CommandResponse = struct {
    command_id: u32 = 0,

    pub const _desc_table = .{
        .command_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InfoRequest = struct {
    body: ?body_union,

    pub const _body_case = enum {
        register_x,
        register_y,
        register_wr,
        register_ww,
        command_status,
        hall_alarm,
        carrier,
        axis,
        station,
    };
    pub const body_union = union(_body_case) {
        register_x: RegisterX,
        register_y: RegisterY,
        register_wr: RegisterWr,
        register_ww: RegisterWw,
        command_status: CommandStatus,
        hall_alarm: HallAlarm,
        carrier: Carrier,
        axis: Axis,
        station: Station,
        pub const _union_desc = .{
            .register_x = fd(3, .{ .SubMessage = {} }),
            .register_y = fd(4, .{ .SubMessage = {} }),
            .register_wr = fd(5, .{ .SubMessage = {} }),
            .register_ww = fd(6, .{ .SubMessage = {} }),
            .command_status = fd(20, .{ .SubMessage = {} }),
            .hall_alarm = fd(21, .{ .SubMessage = {} }),
            .carrier = fd(22, .{ .SubMessage = {} }),
            .axis = fd(26, .{ .SubMessage = {} }),
            .station = fd(27, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const RegisterX = struct {
        line_id: u32 = 0,
        station_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .station_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const RegisterY = struct {
        line_id: u32 = 0,
        station_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .station_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const RegisterWr = struct {
        line_id: u32 = 0,
        station_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .station_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const RegisterWw = struct {
        line_id: u32 = 0,
        station_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .station_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const CommandStatus = struct {
        command_id: u32 = 0,

        pub const _desc_table = .{
            .command_id = fd(1, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const HallAlarm = struct {
        line_id: u32 = 0,
        axis_id: u32 = 0,

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Carrier = struct {
        line_id: u32 = 0,
        param: ?param_union,

        pub const _param_case = enum {
            carrier_id,
            axis_id,
        };
        pub const param_union = union(_param_case) {
            carrier_id: u32,
            axis_id: u32,
            pub const _union_desc = .{
                .carrier_id = fd(2, .{ .Varint = .Simple }),
                .axis_id = fd(3, .{ .Varint = .Simple }),
            };
        };

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .param = fd(null, .{ .OneOf = param_union }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Axis = struct {
        line_id: u32 = 0,
        axis_id: ArrayList(u32),

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .axis_id = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Station = struct {
        line_id: u32 = 0,
        station_id: ArrayList(u32),

        pub const _desc_table = .{
            .line_id = fd(1, .{ .Varint = .Simple }),
            .station_id = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InfoResponse = struct {
    body: ?body_union,

    pub const _body_case = enum {
        register_x,
        register_y,
        register_wr,
        register_ww,
        command_status,
        hall_alarm,
        carrier,
        axis,
        station,
    };
    pub const body_union = union(_body_case) {
        register_x: RegisterX,
        register_y: RegisterY,
        register_wr: RegisterWr,
        register_ww: RegisterWw,
        command_status: CommandStatus,
        hall_alarm: HallAlarm,
        carrier: Carrier,
        axis: Axes,
        station: Stations,
        pub const _union_desc = .{
            .register_x = fd(3, .{ .SubMessage = {} }),
            .register_y = fd(4, .{ .SubMessage = {} }),
            .register_wr = fd(5, .{ .SubMessage = {} }),
            .register_ww = fd(6, .{ .SubMessage = {} }),
            .command_status = fd(20, .{ .SubMessage = {} }),
            .hall_alarm = fd(21, .{ .SubMessage = {} }),
            .carrier = fd(22, .{ .SubMessage = {} }),
            .axis = fd(26, .{ .SubMessage = {} }),
            .station = fd(27, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .body = fd(null, .{ .OneOf = body_union }),
    };

    pub const RegisterX = struct {
        cc_link_enabled: bool = false,
        command_ready: bool = false,
        command_received: bool = false,
        axis_cleared_carrier: bool = false,
        cleared_carrier: bool = false,
        servo_enabled: bool = false,
        emergency_stop_enabled: bool = false,
        paused: bool = false,
        motor_enabled: ?MotorEnabled = null,
        vdc_undervoltage_detected: bool = false,
        vdc_overvoltage_detected: bool = false,
        errors_cleared: bool = false,
        communication_error: ?CommunicationError = null,
        inverter_overheat_detected: bool = false,
        overcurrent_detected: ?OvercurrentDetected = null,
        hall_alarm: ?HallAlarm = null,
        wait_pull_carrier: ?WaitPullCarrier = null,
        wait_push_carrier: ?WaitPushCarrier = null,
        control_loop_max_time_exceeded: bool = false,
        initial_data_processing_request: bool = false,
        initial_data_setting_complete: bool = false,
        error_status: bool = false,
        remote_ready: bool = false,

        pub const _desc_table = .{
            .cc_link_enabled = fd(1, .{ .Varint = .Simple }),
            .command_ready = fd(2, .{ .Varint = .Simple }),
            .command_received = fd(3, .{ .Varint = .Simple }),
            .axis_cleared_carrier = fd(4, .{ .Varint = .Simple }),
            .cleared_carrier = fd(5, .{ .Varint = .Simple }),
            .servo_enabled = fd(6, .{ .Varint = .Simple }),
            .emergency_stop_enabled = fd(7, .{ .Varint = .Simple }),
            .paused = fd(8, .{ .Varint = .Simple }),
            .motor_enabled = fd(9, .{ .SubMessage = {} }),
            .vdc_undervoltage_detected = fd(10, .{ .Varint = .Simple }),
            .vdc_overvoltage_detected = fd(11, .{ .Varint = .Simple }),
            .errors_cleared = fd(12, .{ .Varint = .Simple }),
            .communication_error = fd(13, .{ .SubMessage = {} }),
            .inverter_overheat_detected = fd(14, .{ .Varint = .Simple }),
            .overcurrent_detected = fd(15, .{ .SubMessage = {} }),
            .hall_alarm = fd(16, .{ .SubMessage = {} }),
            .wait_pull_carrier = fd(17, .{ .SubMessage = {} }),
            .wait_push_carrier = fd(18, .{ .SubMessage = {} }),
            .control_loop_max_time_exceeded = fd(19, .{ .Varint = .Simple }),
            .initial_data_processing_request = fd(20, .{ .Varint = .Simple }),
            .initial_data_setting_complete = fd(21, .{ .Varint = .Simple }),
            .error_status = fd(22, .{ .Varint = .Simple }),
            .remote_ready = fd(23, .{ .Varint = .Simple }),
        };

        pub const MotorEnabled = struct {
            axis1: bool = false,
            axis2: bool = false,
            axis3: bool = false,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .Varint = .Simple }),
                .axis2 = fd(2, .{ .Varint = .Simple }),
                .axis3 = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const CommunicationError = struct {
            from_prev: bool = false,
            from_next: bool = false,

            pub const _desc_table = .{
                .from_prev = fd(1, .{ .Varint = .Simple }),
                .from_next = fd(2, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const OvercurrentDetected = struct {
            axis1: bool = false,
            axis2: bool = false,
            axis3: bool = false,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .Varint = .Simple }),
                .axis2 = fd(2, .{ .Varint = .Simple }),
                .axis3 = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const HallAlarm = struct {
            axis1: ?Side = null,
            axis2: ?Side = null,
            axis3: ?Side = null,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .SubMessage = {} }),
                .axis2 = fd(2, .{ .SubMessage = {} }),
                .axis3 = fd(3, .{ .SubMessage = {} }),
            };

            pub const Side = struct {
                back: bool = false,
                front: bool = false,

                pub const _desc_table = .{
                    .back = fd(1, .{ .Varint = .Simple }),
                    .front = fd(2, .{ .Varint = .Simple }),
                };

                pub usingnamespace protobuf.MessageMixins(@This());
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const WaitPullCarrier = struct {
            axis1: bool = false,
            axis2: bool = false,
            axis3: bool = false,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .Varint = .Simple }),
                .axis2 = fd(2, .{ .Varint = .Simple }),
                .axis3 = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const WaitPushCarrier = struct {
            axis1: bool = false,
            axis2: bool = false,
            axis3: bool = false,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .Varint = .Simple }),
                .axis2 = fd(2, .{ .Varint = .Simple }),
                .axis3 = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const RegisterY = struct {
        cc_link_enable: bool = false,
        start_command: bool = false,
        reset_command_received: bool = false,
        axis_clear_carrier: bool = false,
        clear_carrier: bool = false,
        axis_servo_release: bool = false,
        servo_release: bool = false,
        emergency_stop: bool = false,
        temporary_pause: bool = false,
        clear_errors: bool = false,
        reset_pull_carrier: ?ResetPullCarrier = null,
        reset_push_carrier: ?ResetPushCarrier = null,

        pub const _desc_table = .{
            .cc_link_enable = fd(1, .{ .Varint = .Simple }),
            .start_command = fd(2, .{ .Varint = .Simple }),
            .reset_command_received = fd(3, .{ .Varint = .Simple }),
            .axis_clear_carrier = fd(4, .{ .Varint = .Simple }),
            .clear_carrier = fd(5, .{ .Varint = .Simple }),
            .axis_servo_release = fd(6, .{ .Varint = .Simple }),
            .servo_release = fd(7, .{ .Varint = .Simple }),
            .emergency_stop = fd(8, .{ .Varint = .Simple }),
            .temporary_pause = fd(9, .{ .Varint = .Simple }),
            .clear_errors = fd(10, .{ .Varint = .Simple }),
            .reset_pull_carrier = fd(11, .{ .SubMessage = {} }),
            .reset_push_carrier = fd(12, .{ .SubMessage = {} }),
        };

        pub const ResetPullCarrier = struct {
            axis1: bool = false,
            axis2: bool = false,
            axis3: bool = false,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .Varint = .Simple }),
                .axis2 = fd(2, .{ .Varint = .Simple }),
                .axis3 = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const ResetPushCarrier = struct {
            axis1: bool = false,
            axis2: bool = false,
            axis3: bool = false,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .Varint = .Simple }),
                .axis2 = fd(2, .{ .Varint = .Simple }),
                .axis3 = fd(3, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const RegisterWw = struct {
        command: CommandCode = @enumFromInt(0),
        axis: i32 = 0,
        carrier: ?Carrier = null,

        pub const _desc_table = .{
            .command = fd(1, .{ .Varint = .Simple }),
            .axis = fd(2, .{ .Varint = .Simple }),
            .carrier = fd(3, .{ .SubMessage = {} }),
        };

        pub const CommandCode = enum(i32) {
            COMMAND_CODE_UNSPECIFIED = 0,
            NONE = 1,
            SET_LINE_ZERO = 2,
            POSITION_MOVE_CARRIER_AXIS = 3,
            POSITION_MOVE_CARRIER_LOCATION = 4,
            POSITION_MOVE_CARRIER_DISTANCE = 5,
            SPEED_MOVE_CARRIER_AXIS = 6,
            SPEED_MOVE_CARRIER_LOCATION = 7,
            SPEED_MOVE_CARRIER_DISTANCE = 8,
            ISOLATE_FORWARD = 9,
            ISOLATE_BACKWARD = 10,
            CALIBRATION = 11,
            SET_CARRIER_ID_AT_AXIS = 12,
            PUSH_FORWARD = 13,
            PUSH_BACKWARD = 14,
            PULL_FORWARD = 15,
            PULL_BACKWARD = 16,
            PUSH_TRANSITION_FORWARD = 17,
            PUSH_TRANSITION_BACKWARD = 18,
            PULL_TRANSITION_AXIS_FORWARD = 19,
            PULL_TRANSITION_AXIS_BACKWARD = 20,
            PULL_TRANSITION_LOCATION_FORWARD = 21,
            PULL_TRANSITION_LOCATION_BACKWARD = 22,
            _,
        };

        pub const Carrier = struct {
            id: i32 = 0,
            enable_cas: bool = false,
            isolate_link_prev_axis: bool = false,
            isolate_link_next_axis: bool = false,
            speed: i32 = 0,
            acceleration: i32 = 0,
            target: ?target_union,

            pub const _target_case = enum {
                f32,
                u32,
                i32,
            };
            pub const target_union = union(_target_case) {
                f32: f32,
                u32: i32,
                i32: i32,
                pub const _union_desc = .{
                    .f32 = fd(1, .{ .FixedInt = .I32 }),
                    .u32 = fd(2, .{ .Varint = .Simple }),
                    .i32 = fd(3, .{ .Varint = .ZigZagOptimized }),
                };
            };

            pub const _desc_table = .{
                .id = fd(4, .{ .Varint = .Simple }),
                .enable_cas = fd(5, .{ .Varint = .Simple }),
                .isolate_link_prev_axis = fd(6, .{ .Varint = .Simple }),
                .isolate_link_next_axis = fd(7, .{ .Varint = .Simple }),
                .speed = fd(8, .{ .Varint = .Simple }),
                .acceleration = fd(9, .{ .Varint = .Simple }),
                .target = fd(null, .{ .OneOf = target_union }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const RegisterWr = struct {
        command_response: CommandResponse = @enumFromInt(0),
        received_backward: ?CommunicationReceived = null,
        received_forward: ?CommunicationReceived = null,
        carrier: ?Carrier = null,

        pub const _desc_table = .{
            .command_response = fd(1, .{ .Varint = .Simple }),
            .received_backward = fd(2, .{ .SubMessage = {} }),
            .received_forward = fd(3, .{ .SubMessage = {} }),
            .carrier = fd(4, .{ .SubMessage = {} }),
        };

        pub const CommandResponse = enum(i32) {
            COMMAND_RESPONSE_UNSPECIFIED = 0,
            NO_ERROR = 1,
            INVALID_COMMAND = 2,
            CARRIER_NOT_FOUND = 3,
            HOMING_FAILED = 4,
            INVALID_PARAMETER = 5,
            INVALID_SYSTEM_STATE = 6,
            CARRIER_ALREADY_EXISTS = 7,
            INVALID_AXIS = 8,
            _,
        };

        pub const CommunicationReceived = struct {
            id: i32 = 0,
            kind: DriverMessageKind = @enumFromInt(0),
            failed_bcc: bool = false,

            pub const _desc_table = .{
                .id = fd(1, .{ .Varint = .Simple }),
                .kind = fd(2, .{ .Varint = .Simple }),
                .failed_bcc = fd(3, .{ .Varint = .Simple }),
            };

            pub const DriverMessageKind = enum(i32) {
                DRIVER_MESSAGE_KIND_UNSPECIFIED = 0,
                NONE = 1,
                UPDATE = 2,
                PROF_REQ = 3,
                PROF_NOTI = 4,
                UPDATE_CALI_HOME = 5,
                UPDATE_MECH_ANGLE_OFFSET = 6,
                ON_POS_REQ = 7,
                ON_POS_RSP = 8,
                OFF_POS_REQ = 9,
                OFF_POS_RSP = 10,
                CLEAR_CARRIER_INFO = 11,
                _,
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const Carrier = struct {
            axis1: ?Description = null,
            axis2: ?Description = null,
            axis3: ?Description = null,

            pub const _desc_table = .{
                .axis1 = fd(1, .{ .SubMessage = {} }),
                .axis2 = fd(2, .{ .SubMessage = {} }),
                .axis3 = fd(3, .{ .SubMessage = {} }),
            };

            pub const Description = struct {
                location: f32 = 0,
                id: i32 = 0,
                arrived: bool = false,
                auxiliary: bool = false,
                enabled: bool = false,
                quasi: bool = false,
                cas: ?CAS = null,
                state: State = @enumFromInt(0),

                pub const _desc_table = .{
                    .location = fd(1, .{ .FixedInt = .I32 }),
                    .id = fd(2, .{ .Varint = .Simple }),
                    .arrived = fd(3, .{ .Varint = .Simple }),
                    .auxiliary = fd(4, .{ .Varint = .Simple }),
                    .enabled = fd(5, .{ .Varint = .Simple }),
                    .quasi = fd(6, .{ .Varint = .Simple }),
                    .cas = fd(7, .{ .SubMessage = {} }),
                    .state = fd(8, .{ .Varint = .Simple }),
                };

                pub const State = enum(i32) {
                    STATE_UNSPECIFIED = 0,
                    NONE = 1,
                    WARMUP_PROGRESSING = 2,
                    WARMUP_COMPLETED = 3,
                    POS_MOVE_PROGRESSING = 4,
                    POS_MOVE_COMPLETED = 5,
                    SPD_MOVE_PROGRESSING = 6,
                    SPD_MOVE_COMPLETED = 7,
                    AUXILIARY = 8,
                    AUXILIARY_COMPLETED = 9,
                    FORWARD_CALIBRATION_PROGRESSING = 10,
                    FORWARD_CALIBRATION_COMPLETED = 11,
                    BACKWARD_CALIBRATION_PROGRESSING = 12,
                    BACKWARD_CALIBRATION_COMPLETED = 13,
                    FORWARD_ISOLATION_PROGRESSING = 14,
                    FORWARD_ISOLATION_COMPLETED = 15,
                    BACKWARD_ISOLATION_PROGRESSING = 16,
                    BACKWARD_ISOLATION_COMPLETED = 17,
                    FORWARD_RESTART_PROGRESSING = 18,
                    FORWARD_RESTART_COMPLETED = 19,
                    BACKWARD_RESTART_PROGRESSING = 20,
                    BACKWARD_RESTART_COMPLETED = 21,
                    PULL_FORWARD = 22,
                    PULL_FORWARD_COMPLETED = 23,
                    PULL_BACKWARD = 24,
                    PULL_BACKWARD_COMPLETED = 25,
                    PUSH = 26,
                    PUSH_COMPLETED = 27,
                    OVERCURRENT = 28,
                    _,
                };

                pub const CAS = struct {
                    enabled: bool = false,
                    triggered: bool = false,

                    pub const _desc_table = .{
                        .enabled = fd(1, .{ .Varint = .Simple }),
                        .triggered = fd(2, .{ .Varint = .Simple }),
                    };

                    pub usingnamespace protobuf.MessageMixins(@This());
                };

                pub usingnamespace protobuf.MessageMixins(@This());
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const CommandStatus = struct {
        status: Status = @enumFromInt(0),
        error_response: ?ErrorType = null,

        pub const _desc_table = .{
            .status = fd(1, .{ .Varint = .Simple }),
            .error_response = fd(2, .{ .Varint = .Simple }),
        };

        pub const Status = enum(i32) {
            STATUS_UNSPECIFIED = 0,
            PROCESSING = 1,
            COMPLETED = 2,
            FAILED = 3,
            QUEUED = 4,
            _,
        };

        pub const ErrorType = enum(i32) {
            ERROR_UNSPECIFIED = 0,
            CC_LINK_DISCONNECTED = 1,
            VDC_UNDERVOLTAGE_DETECTED = 2,
            VDC_OVERVOLTAGE_DETECTED = 3,
            COMMUNICATION_ERROR_DETECTED = 4,
            INVERTER_OVERHEAT_DETECTED = 5,
            OVERCURRENT_DETECTED = 6,
            CONTROL_LOOP_MAX_TIME_EXCEEDED = 7,
            INVALID_COMMAND = 8,
            CARRIER_NOT_FOUND = 9,
            HOMING_FAILED = 10,
            INVALID_PARAMETER = 11,
            INVALID_SYSTEM_STATE = 12,
            CARRIER_ALREADY_EXISTS = 13,
            INVALID_AXIS = 14,
            UNEXPECTED = 15,
            INVALID_LINE = 16,
            INVALID_STATION = 17,
            _,
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Axes = struct {
        axes: ArrayList(Axis),

        pub const _desc_table = .{
            .axes = fd(1, .{ .List = .{ .SubMessage = {} } }),
        };

        pub const Axis = struct {
            hall_alarm: ?HallAlarm = null,
            motor_enabled: bool = false,
            waiting_pull: bool = false,
            waiting_push: bool = false,
            overcurrent: bool = false,
            carrier_id: u32 = 0,

            pub const _desc_table = .{
                .hall_alarm = fd(1, .{ .SubMessage = {} }),
                .motor_enabled = fd(2, .{ .Varint = .Simple }),
                .waiting_pull = fd(3, .{ .Varint = .Simple }),
                .waiting_push = fd(4, .{ .Varint = .Simple }),
                .overcurrent = fd(5, .{ .Varint = .Simple }),
                .carrier_id = fd(6, .{ .Varint = .Simple }),
            };

            pub const HallAlarm = struct {
                front: bool = false,
                back: bool = false,

                pub const _desc_table = .{
                    .front = fd(1, .{ .Varint = .Simple }),
                    .back = fd(2, .{ .Varint = .Simple }),
                };

                pub usingnamespace protobuf.MessageMixins(@This());
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Stations = struct {
        stations: ArrayList(Station),

        pub const _desc_table = .{
            .stations = fd(1, .{ .List = .{ .SubMessage = {} } }),
        };

        pub const Station = struct {
            connected: bool = false,
            available: bool = false,
            servo_enabled: bool = false,
            stopped: bool = false,
            paused: bool = false,
            errors: ?StationError = null,

            pub const _desc_table = .{
                .connected = fd(1, .{ .Varint = .Simple }),
                .available = fd(2, .{ .Varint = .Simple }),
                .servo_enabled = fd(3, .{ .Varint = .Simple }),
                .stopped = fd(4, .{ .Varint = .Simple }),
                .paused = fd(5, .{ .Varint = .Simple }),
                .errors = fd(6, .{ .SubMessage = {} }),
            };

            pub const StationError = struct {
                control_loop_time_exceeded: bool = false,
                power_error: ?PowerError = null,
                inverter_overheat: bool = false,
                communication_error: ?CommError = null,

                pub const _desc_table = .{
                    .control_loop_time_exceeded = fd(1, .{ .Varint = .Simple }),
                    .power_error = fd(2, .{ .SubMessage = {} }),
                    .inverter_overheat = fd(3, .{ .Varint = .Simple }),
                    .communication_error = fd(4, .{ .SubMessage = {} }),
                };

                pub const PowerError = struct {
                    overvoltage: bool = false,
                    undervoltage: bool = false,

                    pub const _desc_table = .{
                        .overvoltage = fd(1, .{ .Varint = .Simple }),
                        .undervoltage = fd(2, .{ .Varint = .Simple }),
                    };

                    pub usingnamespace protobuf.MessageMixins(@This());
                };

                pub const CommError = struct {
                    from_prev: bool = false,
                    from_next: bool = false,

                    pub const _desc_table = .{
                        .from_prev = fd(1, .{ .Varint = .Simple }),
                        .from_next = fd(2, .{ .Varint = .Simple }),
                    };

                    pub usingnamespace protobuf.MessageMixins(@This());
                };

                pub usingnamespace protobuf.MessageMixins(@This());
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const HallAlarm = struct {
        front: bool = false,
        back: bool = false,

        pub const _desc_table = .{
            .front = fd(1, .{ .Varint = .Simple }),
            .back = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub const Carrier = struct {
        main_axis_id: u32 = 0,
        aux_axis_id: u32 = 0,
        line_id: u32 = 0,
        location: f32 = 0,
        id: u32 = 0,
        state: InfoResponse.RegisterWr.Carrier.Description.State = @enumFromInt(0),
        is_cas_triggered: bool = false,

        pub const _desc_table = .{
            .main_axis_id = fd(1, .{ .Varint = .Simple }),
            .aux_axis_id = fd(2, .{ .Varint = .Simple }),
            .line_id = fd(4, .{ .Varint = .Simple }),
            .location = fd(5, .{ .FixedInt = .I32 }),
            .id = fd(6, .{ .Varint = .Simple }),
            .state = fd(7, .{ .Varint = .Simple }),
            .is_cas_triggered = fd(8, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
