syntax = "proto3";
package mmc.command;

import "mmc/control.proto";
import "range.proto";

// Command API: List of commands to operate the PMF's motion system.
//
// When a command is sent to the server, it will be queued for execution.
// Command execution status can be polled through the Info API. The status
// remains stored in a limited history buffer, and should be cleared with
// `remove_command` after completion.
message Request {
    reserved 2, 10, 17;
    reserved "set_zero", "stop_push", "set_carrier_id";
  oneof body {
    // Calibrate a line. This command only needs to be run once after hardware
    // setup; calibrated values will remain stored in drivers even after a
    // power cycle.
    Calibrate calibrate = 1;
    // Initialize a carrier. Carriers must be initialized before they can be
    // moved. Initialization is required after every power cycle.
    Initialize initialize = 3;
    // Initialize all carriers of the specified line(s). If no lines are
    // specified, initialize all carriers across all lines in the track.
    AutoInitialize auto_initialize = 4;
    // Deinitialize a carrier. This removes all carrier information, such as
    // recognized position and carrier ID.
    Deinitialize deinitialize = 5;
    // Move an initialized carrier to the desired position.
    Move move = 6;
    // Pull and initialize a new carrier into a line.
    Pull pull = 7;
    // Push an initialized carrier to the specified direction.
    Push push = 8;
    // Stop waiting to pull a new carrier at an axis.
    StopPull stop_pull = 9;
    // Release the motor control of a carrier.
    Release release = 11;
    // Clear all errors within the specified driver range.
    ClearErrors clear_errors = 12;
    // Cancel a running command or remove its status history.
    RemoveCommand remove_command = 13;
    // Activate emergency stop for all drivers in line(s). Emergency stop will
    // cause all carriers to decelerate to rest, then reset all carriers'
    // movement commands.
    Stop stop = 14;
    // Activate pause for all drivers in line(s). Pause will cause all
    // carriers to decelerate to rest. On resume, the carriers will continue
    // their previously assigned movement commands.
    Pause pause = 15;
    // Deactivate emergency stop and pause for all drivers in line(s).
    Resume resume = 16;
    // Send multiple moves and push commands at once. The order of execution
    // depends on the order of the move in the buffer. Group move command
    // removes the delay of commands sent to different driver caused by
    // processing time of a driver to fully execute a command. Canceling this
    // command will only cancel commands that are not being executed yet by the
    // target driver.
    Group group = 18;
  }

  message Group {
      repeated CommandGroup commands = 1;
  }

  message CommandGroup {
      oneof command {
          Move move = 1;
          Push push = 2;
      }
  }

  // Release the control imposed by the motor to the carrier. If a target is
  // specified, all motors included in that target release control.
  // Otherwise, all carriers on the provided line will be released from control.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Release {
    // Line ID.
    uint32 line = 1;
    oneof target {
      // Carrier ID.
      uint32 carrier = 2;
      // Axis ID range.
      root.Range axes = 3;
      // Driver ID range.
      root.Range drivers = 4;
    }
  }

  // Stop pulling a carrier to the specified axis. If no axis is provided,
  // then all pending carrier pulls on the line will be stopped.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message StopPull {
    // Line ID.
    uint32 line = 1;
    // Axis ID range.
    optional root.Range axes = 2;
  }

  // Clear all error information on the driver. If a target is specified,
  // clear error information of drivers included in that target. If not,
  // clear error information on all drivers of the specified line ID.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message ClearErrors {
    // Line ID.
    uint32 line = 1;
    oneof target {
      // Driver ID range.
      root.Range drivers = 2;
      // Axis ID range.
      root.Range axes = 3;
      // Carrier ID.
      uint32 carrier = 4;
    }
  }

  // Clear carrier information located on the axis. If a target is specified,
  // clear information of carriers included in that target. If not,
  // clear all carrier information of the specified line ID.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Deinitialize {
    // Line ID.
    uint32 line = 1;
    oneof target {
      // Axis ID range.
      root.Range axes = 2;
      // Driver ID range.
      root.Range drivers = 3;
      // Carrier ID.
      uint32 carrier = 4;
    }
  }

  // Calibrate a line by positioning an uninitialized carrier on the first axis
  // of the line.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Calibrate {
    // Line ID.
    uint32 line = 1;
  }

  // Automatically initialize carriers on every specified lines.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message AutoInitialize {
    message Line {
      reserved 4;
      reserved "velocity_mode";
      // Line ID.
      uint32 line = 1;

      // Velocity of carrier movement. Floating point with range 0.1 - 6,000
      // mm/s (default 600 mm/s).
      optional float velocity = 2;
      // Acceleration of carrier movement. Floating point with range 100 -
      // 24,500 mm/s^2 (default 6000 mm/s^2).
      optional float acceleration = 3;
    }
    repeated Line lines = 1;
  }

  // Move a carrier to the desired position.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Move {
    reserved "velocity_mode", "disable_cas", "velocity", "acceleration";
    reserved 3, 4, 9, 10;
    // Line ID.
    uint32 line = 1;
    // Carrier ID.
    uint32 carrier = 2;

    // Velocity of carrier movement in percent. Maximum velocity 3 m/s.
    uint32 velocity_percent = 11;
    // Acceleration of carrier movement in percent. Maximum acceleration 3 g.
    uint32 acceleration_percent = 12;
    oneof target {
      // Move carrier to the center of the axis.
      uint32 axis = 5;
      // Move carrier to relative location to the zero-point of the line,
      // which is set by default at the center of the line's first axis after
      // calibration command.
      float location = 6;
      // Move carrier to relative distance to current carrier position. Negative
      // distance moves the carrier backwards.
      float distance = 7;
    }
    // Control method for moving carrier.
    mmc.Control control = 8;
  }

  // Push an initialized carrier to the specified direction.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Push {
    reserved "velocity_mode", "velocity", "acceleration";
    reserved 4, 5, 7;
    // Line ID.
    uint32 line = 1;
    // Axis ID.
    uint32 axis = 2;
    // Direction of carrier movement.
    Direction direction = 3;

    // Velocity of carrier movement in percent. Maximum velocity 3 m/s.
    uint32 velocity_percent = 8;
    // Acceleration of carrier movement in percent. Maximum acceleration 3 g.
    uint32 acceleration_percent = 9;
    // Carrier ID. If provided, wait for the specified carrier at the axis and
    // push it once the carrier arrives.
    optional uint32 carrier = 6;
  }

  // Pull and initialize a new carrier into a line.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Pull {
    reserved "velocity_mode", "velocity";
    reserved 5, 6, 8;
    // Line ID.
    uint32 line = 1;
    // Axis ID.
    uint32 axis = 2;
    // ID for the incoming carrier.
    uint32 carrier = 3;
    // The direction from which the incoming carrier is moving.
    Direction direction = 4;

    // Velocity of carrier movement in percent. Maximum velocity 3 m/s.
    uint32 velocity_percent = 9;
    // Acceleration of carrier movement in percent. Maximum acceleration 3 g.
    uint32 acceleration_percent = 10;
    // Smoothly transition to carrier movement after pull completion.
    optional Transition transition = 7;

    message Transition {
      reserved "axis", "location", "distance", "disable_cas";
      reserved 2 to 5;
      // Control method for moving carrier.
      mmc.Control control = 1;
      // Move carrier to relative location to the zero-point of the line,
      // which is set by default at the center of the line's first axis after
      // calibration, but can also be set with the `SetZero` command.
      // Pass NaN to pull carrier without motor control, allowing carrier
      // to be pulled with external force.
      float target = 6;
    }
  }

  // Initialize a carrier.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Initialize {
    // Line ID.
    uint32 line = 1;
    // Axis ID.
    uint32 axis = 2;
    // ID for the new carrier.
    uint32 carrier = 3;
    // Initialization direction for the new carrier.
    Direction direction = 4;
    // Linked axis direction from the specified axis.
    optional Direction link_axis = 5;
  }

  // Remove a command on the server if the command ID is specified. If no
  // command ID is specified, remove any commands received by the server. If
  // the commands are still progressing, cancel the command execution.
  //
  // Expected response: `mmc.Response.body.command.body.removed_id` (uint32).
  message RemoveCommand {
    // Command ID.
    optional uint32 command = 1;
  }

  // Send an emergency stop command to stop any operation in PMF LMS. This
  // command also removes all queued commands in the server.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Stop {
    // Line ID. If provided, stop operations only on the specified lines and
    // remove all commands that targeting those lines.
    repeated uint32 lines = 1;
  }

  // Pause any operation in PMF LMS. Any queued commands in the server will be
  // continued once the resume command is given.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Pause {
    // Line ID. If provided, pause operations only on the specified lines.
    repeated uint32 lines = 1;
  }

  // Resume lines that have been stopped or paused. If the line is not paused
  // or emergency stopped, this command will succeed without any effect.
  //
  // Expected response: `mmc.Response.body.command.body.id` (uint32).
  message Resume {
    // Line ID. If provided, resume operations only to those specified lines.
    repeated uint32 lines = 1;
  }

  enum Direction {
    DIRECTION_UNSPECIFIED = 0;
    DIRECTION_BACKWARD = 1;
    DIRECTION_FORWARD = 2;
  }

  enum Error {
    reserved 13;
    reserved "COMMAND_REQUEST_ERROR_CC_LINK_DISCONNECTED";

    COMMAND_REQUEST_ERROR_UNSPECIFIED = 0;
    // Attempted to use line ID outside of the configured lines.
    COMMAND_REQUEST_ERROR_INVALID_LINE = 1;
    // Attempted to use axis ID outside of the configured axes of the line.
    COMMAND_REQUEST_ERROR_INVALID_AXIS = 2;
    // Attempted to use driver ID outside of the configured drivers of the line.
    COMMAND_REQUEST_ERROR_INVALID_DRIVER = 3;
    // Attempted to use acceleration value outside of 1-245.
    COMMAND_REQUEST_ERROR_INVALID_ACCELERATION = 4;
    // Attempted to use velocity value outside of 1-60.
    COMMAND_REQUEST_ERROR_INVALID_VELOCITY = 5;
    // Using invalid direction for the command.
    COMMAND_REQUEST_ERROR_INVALID_DIRECTION = 6;
    // Deprecated. Check `COMMAND_ERROR_INVALID_CARRIER_TARGET` on
    // `Info.Response.Command.Error`.
    COMMAND_REQUEST_ERROR_INVALID_LOCATION = 7 [deprecated = true];
    // Deprecated. Check `COMMAND_ERROR_INVALID_CARRIER_TARGET` on
    // `Info.Response.Command.Error`.
    COMMAND_REQUEST_ERROR_INVALID_DISTANCE = 8 [deprecated = true];
    // Attempted to send a command to carrier outside of 1-2048.
    COMMAND_REQUEST_ERROR_INVALID_CARRIER = 9;
    // A command missing the required parameter.
    COMMAND_REQUEST_ERROR_MISSING_PARAMETER = 10;
    // Attempted to remove or cancel a non-existing command.
    COMMAND_REQUEST_ERROR_COMMAND_NOT_FOUND = 11;
    // Attempted to send command to an uninitialized carrier.
    COMMAND_REQUEST_ERROR_CARRIER_NOT_FOUND = 12;
    // Server unable to receive new command caused by out of memory.
    // Try `Command.Request.remove_command` to free the memory.
    COMMAND_REQUEST_ERROR_OUT_OF_MEMORY = 14;
    // Attempted to run more than 8 auto initialize instance.
    COMMAND_REQUEST_ERROR_MAXIMUM_AUTO_INITIALIZE_EXCEEDED = 15;
    // Attempted to assign a carrier ID that is already used by
    // another carrier on the same line.
    COMMAND_REQUEST_ERROR_CONFLICTING_CARRIER_ID = 16;
    // Command index is out of bounds for the configured command status buffer.
    COMMAND_REQUEST_ERROR_INVALID_COMMAND = 17;
  }
}

// Response description to the command API.
message Response {
  oneof body {
    // Assigned ID for newly sent command.
    uint32 id = 1;
    // ID of cleared existing command.
    uint32 removed_id = 3;
    // Error during command's execution.
    Request.Error request_error = 2;
  }
}
